{% set version = "1.1.9" %}
{% set sha256 = "75c1fbb3d618dd3a0483bff0e26d0a92b495bbe5059c8b4f1c962b478b6e06e7" %}

package:
  name: snappy
  version: {{ version }}

source:
  - url: https://github.com/google/snappy/archive/{{ version }}.tar.gz
    fn: snappy-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - Add_inline.patch

  # these are git submodules
  - url: https://github.com/google/benchmark/archive/bf585a2789e30585b4e3ce6baf11ef2750b54677.tar.gz
    sha256: 8222ebe7d9049c4b8bb3f930e3ca08e232f5587ad4121619f73f6ce374391c70
    folder: third_party/benchmark
  - url: https://github.com/google/googletest/archive/18f8200e3079b0e54fa00cb7ac55d4c39dcf6da6.tar.gz
    sha256: d518c1c146c5a87cdedbee8535a396f95d91e8b39baa539fd4c50bd62148d199
    folder: third_party/googletest

build:
  number: 0
  run_exports:
    # other than a fluke at 1.1.5, it's stable
    #   https://abi-laboratory.pro/tracker/timeline/snappy/
    - {{ pin_subpackage('snappy', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - cmake
    - git
    - m2-patch   # [win]
    - patch  # [not win]
  host:
    - msinttypes  # [win and vc<14]

test:
  commands:
    - test -e $PREFIX/include/snappy.h               # [unix]
    - test -e $PREFIX/include/snappy-stubs-public.h  # [unix]
    - test -e $PREFIX/lib/libsnappy$SHLIB_EXT        # [unix]
    - test -e $PREFIX/lib/libsnappy.a                # [unix]
    - if not exist %LIBRARY_INC%\snappy.h exit 1               # [win]
    - if not exist %LIBRARY_INC%\snappy-stubs-public.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\snappy.lib exit 1             # [win]
    - if not exist %LIBRARY_BIN%\snappy.dll exit 1             # [win]
    - if not exist %LIBRARY_LIB%\snappy_static.lib exit 1      # [win]

about:
  home: https://github.com/google/snappy
  license: BSD-3-clause AND CC-BY-3.0 AND MIT AND CC-BY AND Public Domain
  license_file: COPYING
  license_family: BSD
  summary: A fast compressor/decompressor
  description: |
    Snappy is a compression/decompression library. It does not aim for maximum
    compression, or compatibility with any other compression library; instead, it
    aims for very high speeds and reasonable compression. For instance, compared to
    the fastest mode of zlib, Snappy is an order of magnitude faster for most
    inputs, but the resulting compressed files are anywhere from 20% to 100%
    bigger.
  dev_url: https://github.com/google/snappy
  doc_url: https://github.com/google/snappy/tree/master/docs

extra:
  recipe-maintainers:
    - groutr
    - jakirkham
    - wesm
    - xhochy
    - dougalsutherland
    - MaxRis
