travis:
  secure:
    BINSTAR_TOKEN: FPcqIZhfmOkuPIfQ4+kgaAH0Oi7AifrgqSlUCEsWjpP1hd0/k9DKg8q5qyh+PoBy8KDAfHoiGOrypnO2pFqqRj9F+R4B/jYlReEECN6aG0tMRiOLFGitaUJotx32iTUUrfOiUDKZpVxtgpq70oXtD+R+I/fKmbt9UXlML4CfxwqxZ36khS8syug5RoeF5hgJNLT/2K8FrhO9FzRAuOnnVQo1RkmV3QTbW8TbvNd+eDiihKZUPl6r0x3xyKPSIc03rxVpB5mYQBlI6MHm8gkkPblM9/PYaB+4EWC/P/eqfDOalXQZlpTM+M5MHJvKZo8W+h8b97FdeGWUX/1wQcE7iIcwGRUc08Y+oDRFT2sQNqriLdJbpGhz5bXHofnu7QtTF2IwOX8wxuGPRMuxKaT+zzJxlyeLR4f0t7KosHx5TGuO5BGOu3SOmjot45hc4zWjAYPbjetez+dOC8Nt+EP0xU2maYe1xTwoAZh536SLvL3fHExG9/0gcEmyOhF+z9ZDW/nSrX19lEhVCiFpZnt7MZUYJpYxz8WlfCMxn5tJbdrZ7gGAOiXoVy3HF+LoVlQw6Rf6Tt56JmaYD+OW/MKNczKJIYn1MbiSdKFqF5kq7oC0HVeUtBLP9KICHie3qiODq9zKJMsrXVnogN7YV7VQfziHEBtPzyru/84K2/MHKyM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
